name: Publish to VS Code MarketPlace

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4

            - name: Get latest tag
              run: |
                  latest-tag=$(git describe --tags --abbrev=0)
                  echo "Latest tag: $latest-tag"
                  echo "LATEST_TAG=$latest-tag" >> $GITHUB_ENV

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install dependencies
              run: |
                  npm ci
                  npm install -g vsce

            - name: Update version in package.json
              run: |
                  jq --arg version "$LATEST_TAG" '.version = $version' package.json > package.tmp.json
                  mv package.tmp.json package.json
              shell: bash

            - name: Verify updated package.json
              run: cat package.json

            - name: Replace sentry_dns with SENTRY_URL from secrets
              run: |
                  sed -i "s#https://5427545a2216287c2e4e0fc546172a6a@sentry.debricked.com/20#${{ secrets.SENTRY_URL }}#g" ./src/constants/organization.ts
              shell: bash

            - name: Verify updated organization.ts
              run: cat ./src/constants/organization.ts
              
            - name: Package VS Code Extension
              run: vsce package

            - name: Upload VSIX artifact
              uses: actions/upload-artifact@v3
              with:
                  name: vsce-package
                  path: "*.vsix"
            # - name: Publish to VS Code Marketplace
            #   env:
            #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
            #   run: vsce publish -p $VSCE_PAT
            - name: Trigger Sentry Release
              uses: ./.github/workflows/sentry-release.yml
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                
            
