name: Publish to VS Code MarketPlace

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: | 
          npm ci
          npm install -g vsce
      - name: Package
        run: vsce package
      - name: Publish
        env:
          VSCE_PAT: secrets.VSCE_PAT
        run: vsce publish -p $VSCE_PAT