name: Publish to VS Code MarketPlace & update Sentry

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        outputs:
            package-lock-hash: ${{ runner.os }}-repo-${{ steps.hash.outputs.hash }}
            latest-tag: ${{ steps.hash.outputs.latest-tag }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Get latest tag
              run: |
                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
                  echo "latest-tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
              shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

            - name: Install dependencies
              run: |
                  npm ci
                  npm install -g vsce
                  npm install -g @sentry/cli

            - name: Calculate package-lock.json hash
              id: hash
              run: echo "hash=$(sha256sum package-lock.json | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"

            - name: Cache repository
              uses: actions/cache@v4
              with:
                  path: .
                  key: ${{ runner.os }}-repo-${{ steps.hash.outputs.hash }}

    build:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Restore repository cache
              uses: actions/cache@v4
              with:
                  path: .
                  key: ${{ needs.setup.outputs.package-lock-hash }}
                  fail-on-cache-miss: true
            - name: Compile
              run: |
                  npm run compile-tests
                  npm run compile

            - name: Cache repository
              uses: actions/cache@v4
              with:
                  path: .
                  key: ${{ runner.os }}-repo-${{ needs.setup.outputs.package-lock-hash }}

    package:
        runs-on: ubuntu-latest
        needs: [setup, build]
        steps:
            - name: Restore repository cache
              uses: actions/cache@v4
              with:
                  path: .
                  key: ${{ needs.setup.outputs.package-lock-hash }}
                  fail-on-cache-miss: true

            - name: Update version in package.json
              run: |
                  jq --arg version "${{ needs.setup.outputs.latest-tag }}" '.version = $version' -i package.json
              shell: bash

            - name: Verify updated package.json
              run: cat package.json

            - name: Package VS Code Extension
              run: vsce package

            - name: Upload VSIX artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vsce-package
                  path: "*.vsix"

            - name: List folders
              run: |
                  ls -l
