name: Sentry Release

on:
    workflow_dispatch:

jobs:
    sentry-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Get latest tag
              run: |
                  latest-tag=$(git describe --tags --abbrev=0)
                  echo "Latest tag: $latest-tag"
                  echo "LATEST_TAG=$latest-tag" >> $GITHUB_ENV
                  
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
                  SENTRY_URL: ${{ secrets.SENTRY_URL }}
              with:
                  environment: production
                  version: "$LATEST_TAG"
